[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"

[project]
name = "hello-claude"
dynamic = ["version"]
description = ""
readme = "README.md"
requires-python = ">=3.10"
license = {text = "Apache-2.0"}
authors = [{name = "tecount-fr", email = "87020468+tecount-fr@users.noreply.github.com"}]
keywords = ['nbdev']
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
]
dependencies = []

[project.urls]
Repository = "https://github.com/tecount-fr/hello-claude"
Documentation = "https://tecount-fr.github.io/hello-claude/"

[project.entry-points.nbdev]
hello_claude = "hello_claude._modidx:d"

[tool.setuptools.dynamic]
version = {attr = "hello_claude.__version__"}

[tool.setuptools.packages.find]
include = ["hello_claude"]

[tool.nbdev]
